from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field
from app.core.config import settings


class SEOMetadata(BaseModel):
    """
    Data model representing the structured SEO metadata generated by the AI.
    """

    meta_title: str = Field(description="The SEO-optimized title for the document.")
    meta_description: str = Field(
        description="The SEO-optimized description or meta summary for the document."
    )
    meta_routes: list[str] = Field(
        description="A list of 3-5 suggested URL routes or slugs suitable for the document content."
    )


async def generate_seo_metadata(parsed_content: str, primary_keyword: str) -> SEOMetadata:
    """Generates SEO metadata from extracted document content and primary keyword using Langchain and Groq."""

    # Check if GROQ_API_KEY is available
    if not settings.GROQ_API_KEY:
        raise ValueError("GROQ_API_KEY not found in environment variables.")

    # Initialize the Groq Chat model
    llm = ChatGroq(
        model_name=settings.GROQ_MODEL,
        groq_api_key=settings.GROQ_API_KEY,
        temperature=0.4,
        max_retries=3,
        model_kwargs={"top_p": 0.9},
    )

    # By using structured output with method="json_mode" we force the model to
    # output strict JSON instead of spending tokens reasoning or chatting.
    structured_llm = llm.with_structured_output(SEOMetadata, method="json_mode")

    # Configure the schema output via Prompt Instructions
    prompt = PromptTemplate.from_template(
        """
       <|header_start|>system<|header_end|>: You are a senior SEO strategist and conversion copywriter.
 
        Audience: Devs, founders, product managers, and non-technical readers.
 
        Task: Analyze the given content and output structured SEO metadata that improves CTR and follows Google SEO best practices for the Blog Post.
 
        The Primary Keyword for this blog post is: "{primary_keyword}"
 
        RULES:
        1. META TITLE (40-60 characters, hard limit include spaces):
            - Analyze the Blog Content and create a descriptive and keyword-rich title
            - What the reader gets value-driven and action-oriented language.
            - Include the primary keyword naturally
 
       
        2. META DESCRIPTION (140-160 characters, hard limit include spaces):
            - Open with a sharp conversational line that mirrors the reader's search intent.
            - Name specific things directly from the blog content — no filler.
            - Naturally weave in the primary keyword without forcing it
            - Match the search intent of the Blog Content and Tone : Conversational, speaks directly to reader , not an ad ,no invented claims
            - Natural verbs only
 
        3. URL ROUTES (5 slugs):
            - Derived from Key topics in the Blog Content
            - Lowercase and hyphens only — no dates, years, numbers.
            - Each slug must be a descriptive phrase, not a shortened fragment
 
        CONSTRAINTS:
            - No dates, years, or commentary in output
            - Every claim from Blog only — never invent
            - Read every field aloud before finalizing — if it sounds clipped or robotic, rewrite it
            - Output ONLY valid JSON
 
        OUTPUT SCHEMA:
        {{
            "meta_title": "string",
            "meta_description": "string",
            "meta_routes": ["string", "string", "string", "string", "string"]
        }}
 
        <document>
        {content}
        </document>
        """
    )

    chain = prompt | structured_llm

    try:
        result = await chain.ainvoke({"content": parsed_content, "primary_keyword": primary_keyword})
    except Exception as api_err:
        print(
            f"[AI Generator] API call FAILED — model '{settings.GROQ_MODEL}' may be invalid or unsupported."
        )
        print(f"[AI Generator] API error: {api_err}")
        return SEOMetadata(
            meta_title="Failed to generate SEO Title",
            meta_description="API call failed. Check that the model name in config.py is a valid Groq model.",
            meta_routes=["error-generating-routes"],
        )

    # We skip regex extraction, because structured output guarantees parsing
    try:
        return result
    except Exception as e:
        print(f"[AI Generator] Error parsing LLM output: {e}")
        # Return fallback
        return SEOMetadata(
            meta_title="Failed to generate SEO Title",
            meta_description="Error parsing LLM response.",
            meta_routes=["error-generating-routes"],
        )
